<!DOCTYPE html>
<html>
<head>
    <title>Languages</title>
</head>
<body>
    <h1>Use these resources to learn a programming languages:</h1>
    <h3>Languages are sorted by popularity.</h3>
    <table>
        <thead>
            <tr>
                <th>Language</th>
                <th>Oct 2014</th>
                <th>Oct 2015</th>
                <th>Change</th>
                <th>Ratings</th>
                <th>Difference</th>
            </tr>
        </thead>
        <tr>
            <td>Java</td>
            <td>2</td>
            <td>1</td>
            <td>UP</td>
            <td>19.543%</td>
            <td></td>
        </tr>
        <tr>
            <td>C</td>
            <td></td>
            <td></td>
            <td>DOWN</td>
            <td>16.190%</td>
            <td></td>
        </tr>
        <tr>
            <td>C++</td>
            <td></td>
            <td></td>
            <td>UP</td>
            <td>5.749%</td>
            <td></td>
        </tr>
        <tr>
            <td>C#</td>
            <td></td>
            <td></td>
            <td>UP </td>
            <td>4.825%</td>
            <td></td>
        </tr>
        <tr>
            <td>Python</td>
            <td></td>
            <td></td>
            <td></td>
            <td>4.512%</td>
            <td></td>
        </tr>
        <tr>
            <td>PHP</td>
            <td></td>
            <td></td>
            <td></td>
            <td>2.561%</td>
            <td></td>
        </tr>
        <tr>
            <td>Visual Basic .NET</td>
            <td></td>
            <td></td>
            <td></td>
            <td>2.462%</td>
            <td></td>
        </tr>
        <tr>
            <td>JavaScript</td>
            <td></td>
            <td></td>
            <td></td>
            <td>2.292%</td>
            <td></td>
        </tr>
        <tr>
            <td>Perl</td>
            <td></td>
            <td></td>
            <td></td>
            <td>2.247%</td>
            <td></td>
        </tr>
        <tr>
            <td>Ruby</td>
            <td></td>
            <td></td>
            <td></td>
            <td>1.825%</td>
            <td></td>
        </tr>
        <tr>
            <td>Delphi/Object Pascal</td>
            <td></td>
            <td></td>
            <td></td>
            <td>1.637%</td>
            <td></td>
        </tr>
        <tr>
            <td>Assembly Language</td>
            <td></td>
            <td></td>
            <td></td>
            <td>1.573%</td>
            <td></td>
        </tr>
        <tr>
            <td>Visual Basic</td>
            <td></td>
            <td></td>
            <td></td>
            <td>1.515%</td>
            <td></td>
        </tr>
        <tr>
            <td>Objective-C</td>
            <td></td>
            <td></td>
            <td></td>
            <td>1.419%</td>
            <td></td>
        </tr>
        <tr>
            <td>Swift</td>
            <td></td>
            <td></td>
            <td></td>
            <td>1.277%</td>
            <td></td>
        </tr>
        <tr>
            <td>Pascal</td>
            <td></td>
            <td></td>
            <td></td>
            <td>1.194%</td>
            <td></td>
        </tr>
        <tr>
            <td>MATLAB</td>
            <td></td>
            <td></td>
            <td></td>
            <td>1.159%</td>
            <td></td>
        </tr>
        <tr>
            <td>PL/SQL</td>
            <td></td>
            <td></td>
            <td></td>
            <td>1.067%</td>
            <td></td>
        </tr>
        <tr>
            <td>OpenEdge ABL</td>
            <td></td>
            <td></td>
            <td></td>
            <td>1.040%</td>
            <td></td>
        </tr>
        <tr>
            <td>R</td>
            <td></td>
            <td></td>
            <td></td>
            <td>0.991%</td>
            <td></td>
        </tr>
    </table>
</body>
</html>
